# yamllint disable rule:braces rule:commas rule:colons rule:comments-indentation
---
window:
    # Blank space added around the window in pixels
    padding:
        x: 0
        y: 0

    # Spread additional padding evenly around the terminal content
    dynamic_padding: true
    
    opacity : 0.7

    # Disable border and title bar
    #decorations: none

font:
    normal:
        family: Hack Nerd Font Mono
        style: Regular
    bold:
        family: Hack Nerd Font Mono
        style: Bold
    italic:
        family: Hack Nerd Font Mono
        style: Italic

    # Point size of the font
    size: 11.5

mouse:
    hide_when_typing: true

selection:
    # When set to `true`, selected text will be copied to the primary
    # clipboard.
    save_to_clipboard: true
